[package]
name = "tf-demo-parser"
description = "parser for tf2 demo files"
version = "0.4.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/demostf/parser"
exclude = [ "tests/fuzz", "test_data" ]
default-run = "parse_demo"

[lib]
name = "tf_demo_parser"
path = "src/lib.rs"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib"]

[[bin]]
name = "parse_demo"
path = "src/bin/main.rs"

[[bin]]
name = "reencode_demo"
path = "src/bin/reencode.rs"

[[bin]]
name = "gamestate"
path = "src/bin/gamestate.rs"

[[bin]]
name = "schema"
path = "src/bin/schema.rs"
required-features = ["schema"]

[dependencies]
bitbuffer = { version = "0.10.9", features = ["serde"] }
num_enum = "0.5.7"
num-traits = "0.2.15"
enumflags2 = { version = "0.7.5", features = ["serde"] }
snap = "1.1.0"
serde = { version = "1.0.152", features = ["derive", "rc"] }
serde_json = "1.0.91"
serde_repr = "0.1.10"
err-derive = "0.3.1"
parse-display = "0.8.0"
main_error = "0.1.2"
jemallocator = { version = "0.5.0", optional = true }
better-panic = { version = "0.3.0", optional = true }
no-panic = { version = "0.1.17", optional = true }
fnv = "1.0.7"
steamid-ng = "1.0.0"
schemars = { version = "0.8.11", optional = true }
tracing = { version = "0.1.37", optional = true }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"], optional = true }
itertools = "0.10.5"
pyo3 = { version = "0.17.1", features = ["extension-module"] }

[features]
schema = ["schemars", "bitbuffer/schemars"]
trace = ["tracing", "tracing-subscriber"]

[dev-dependencies]
pretty_assertions = "1.3.0"
test-case = "2.2.2"
iai = "0.1.1"
criterion = "0.4.0"

[profile.release]
lto = true

[profile.dev]
opt-level = 2

[[bench]]
name = "iai"
harness = false

[[bench]]
name = "allmessages"
harness = false

[[bench]]
name = "bench"
harness = false

[[bench]]
name = "sendprop"
harness = false
